name: hanoigo
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ">=3.4.4 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  dio: ^5.7.0
  retrofit: ^4.4.1
  freezed_annotation: ^2.4.4
  json_annotation: ^4.9.0
  shared_preferences: ^2.3.2
  gap: ^3.0.1
  flutter_mobx: ^2.2.1+1
  mobx: ^2.4.0
  mobx_codegen: ^2.6.2
  get: ^4.6.6
  flutter_svg: ^2.0.15
  vector_graphics: ^1.1.15
  image_picker: ^1.1.2
  permission_handler: ^11.3.1
  mobile_scanner: ^6.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0
  build_runner: ^2.4.11
  freezed: ^2.5.2
  retrofit_generator: ^8.2.1
  json_serializable: ^6.8.0
  flutter_gen: ^5.8.0
  flutter_gen_runner: ^5.8.0

flutter_gen:
  output: lib/generated/
  line_length: 120

  integrations:
    flutter_svg: true
    flare_flutter: true
    rive: true
    lottie: true

  colors:
    inputs:
      - assets/colors/colors.xml

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/icons/
    - assets/fonts/

  fonts:
    - family: WorkSans
      fonts:
        - asset: assets/fonts/WorkSans-Regular.ttf
